### ISSUE TITLE
Turn LibtaskBuilder2 into a independent package  

### ISSUE THREAD

**Issue by yebai** [hessammehr/LibtaskBuilder2#3]
Hi @hessammehr, I suggest that we 

- move the `task.c` file and relevant tests from Turing into `LibtaskBuilder2`
- rename `LibtaskBuilder2` to `Libtask`?
- make `Turing` depend on `Libtask`?

I think this will improve code organisation, what do you think? Let me know your thoughts!

#https://github.com/TuringLang/Turing.jl/issues/466

**Comment by hessammehr** [comment]
Hi @yebai. I think we'll need to keep LibtaskBuilder around just to be able to produce the binary artifacts, but I'll create a new TuringLang project with task.c in it. Absolutely agree on code organisation. I will also transfer ownership of LibtaskBuilder to the TuringLang org.
